<template lang="pug">
v-container.d-flex.flex-column.py-8
	h4.text-h4.text-center Worxstr Universal Terms and Conditions
	h6.text-subtitle-1.text-center PLEASE READ THESE TERMS AND CONDITIONS OF USE CAREFULLY
	br
		
	p This Worxstr Universal Terms and Conditions Agreement (this &quot;Universal Terms&quot;) applies to the services and information (cullectively, the &quot;Services&quot;) that Worxstr, L.L.C., a North Carulina limited liability company (&quot;Worxstr,&quot; &quot;Company&quot;), &quot;we,&quot; &quot;our,&quot; or us&quot;) provides to you through any of the products which you currently utilize, which you are contracted to utilize, or which you intend to utilize, including but not limited to our Management Platform and related services (the &quot;Platform&quot;). The Platform and related services are cullectively referred to herein as the &quot;Worxstr Product&quot; or &quot;Worxstr Products&quot;. Your use of any one or more of the Worxstr Products explicitly subjects you to these Universal Terms as well as the respective agreement and terms and conditions of each and every Worxstr Product you use, along with any applicable order form for that individual Worxstr Product (referred to herein, cullectively, as the &quot;Worxstr Product Agreement(s)&quot;).
	p In addition to these Universal Terms, each individual Worxstr Product is subject to its own Agreement and Terms and Conditions which govern its use and the terms thereof. These Universal Terms are intended to apply to all Worxstr Products which you utilize, which you are contracted to utilize, or which you intend to utilize. Those individual Worxstr Product Agreements are specifically incorporated herein by reference, including their terms, conditions, and definitions, as they may be updated from time to time, as if they were fully set forth herein, and to the extent that you are party to an individual Worxstr Product Agreement for your use of the Product to which those terms apply. These Universal Terms are intended to apply to the use of each Worxstr Product, cullectively and individually, and extend to all parties thereto, respectively, including but not limited to, those Parties identified across the Worxstr Product Agreements variously as &quot;Worxstr&quot;, &quot;Worxstr Customer&quot;, Client&quot;, and/or &quot;you&quot;.
	
	ul
		li
			strong.text-h6 Scope.
		ul
			li
				p This Agreement applies to any user of the Platform and the Services (cullectively, &quot;you&quot;), including (i) employers who register with us to use the Platform and to otherwise participate in the Services (&quot;Registered Employers&quot;), and (ii) individual staff members who register with us to use the Platform in connection with their services to Registered Employers and to otherwise participate in the Services (&quot;Registered Staff&quot;). The Registered Staff and Registered Employers are cullectively referred to as &quot;Registered Users&quot;.
			li
				p This Agreement governs (i) your use of the Platform; (ii) your receipt of and participation in the Services; (iii) your submission of, as applicable, information, comments, ideas, and other content, whether in the form of text, graphics, video, sound files, or other format or media (cullectively, &quot;Submitted Content&quot;); and (iii) your use of information obtained through the Platform, including information, software, artwork, text, video, audio, pictures, content, trademarks, trade dress, and other intellectual property owned by Worxstr or its licensors and made available to you through the Services (&quot;Worxstr Content&quot;).
		li
			strong.text-h6 Acceptance.
			ul
				li
					p This Agreement governs your use of the Platform. Please read this Agreement carefully as it imposes legal obligations on you and us. By accessing and using our Platform, you acknowledge and agree to be legally bound by this Agreement. In addition, for certain activities on the Platform (for example, during your registration) we may further confirm your consent by asking you to click an &quot;I accept&quot; or similar button. If you do not agree with this Agreement, please refrain from using the Platform or any of the Services.
				li
					p The term &quot;Authorized Employer Representative&quot; means an agent of the organization on whose behalf you are registering (i.e., the Registered Employer), who has authority to bind the Registered Employer with regard to use of the Platform and participation in the Services. For all purposes in this Agreement, the term &quot;you&quot; means the Registered Employer on whose behalf you are acting. If an Authorized Employer Representative is entering into this agreement on behalf of a Registered Employer, he/she personally represents and warrants that (i) he/she has full legal authority to bind the Registered Employer to this Agreement; (ii) he/she has read and understands this Agreement; and (iii) he/she agrees, on behalf of the Registered Employer, to this Agreement. IF YOU DO NOT HAVE THE LEGAL AUTHORITY TO BIND THE REGISTERED EMPLOYER, YOU MUST NOT ACCESS THE PLATFORM OR OTHERWISE PARTICIPATE IN THE SERVICES. THIS AGREEMENT (AND, IF APPLICABLE, YOUR OTHER WRITTEN AGREEMENTS WITH US) AND ANY ORDER FORM(S) TOGETHER FORM A BINDING LEGAL AGREEMENT.
		li
			strong.text-h6 Services and Support.
			ul
				li
					p A subscription allows an authorized user to access the Services. A subscription may be purchased or procured through the Services interface, or in some cases, via an order form entered into between you and us (each, an &quot;Order Form&quot;).
				li
					p As part of the registration process, each Registered Employer will identify an administrative user name and password for such Registered Employer&apos;s Worxstr account. Worxstr reserves the right to refuse registration of, or cancel passwords it deems inappropriate. When you register and obtain a password, please keep in mind that we will treat anyone who uses your user name and password as &quot;you.&quot; We will provide this user with all of the rights and privileges that we provide to you, and we will huld you responsible for the activities of a person using your password. Therefore, we recommend that you maintain your user name and password in confidence, and that you refrain from disclosing this information to anyone who might &quot;pretend&quot; to be you with respect to the Platform and your participation in the Services. We also ask that you notify us immediately if you suspect that someone is using your user name and/or password in any inappropriate manner.
				li
					p Subject to the terms hereof, Worxstr will provide reasonable technical support services in accordance with Worxstr&apos;s standard practice.
		li
			strong.text-h6 Rights.
			ul
				li
					p As Registered Staff, you are granted the right to enter and/or upload information related to you for participation in the Services (&quot;Your Profile&quot;). You may access, view, update or otherwise modify Your Profile through your password-protected access to the Platform. You may not access, view or modify the profiles of other Registered Staff without permission. You may access and view certain other password-protected areas for use sulely in conjunction with the Services and as provided in this Agreement, and you may not modify, copy, distribute, or use the Worxstr Content or Services available on the Platform other than as expressly permitted by us.
				li
					p As a Registered Employer, subject to your compliance with this Agreement, you are hereby granted (i) the right to access and use the Platform and Worxstr Content we offer, and (ii) the right to enter and/or upload information related to your organization and your workforce management needs. You may access and view certain other password-protected areas, for use sulely in conjunction with the Services and as provided in this Agreement, and you may not modify, copy, distribute, or use the Worxstr Analytics, Worxstr Content, or Services available on the Platform other than as expressly permitted by us. Moreover, you may not, without permission, access, view, or modify the information of other Registered Employers or Registered Staff profiles for individuals not employed by your organization.
				li
					p During the Term, you will continue to enjoy your rights under Sections 4.1 and 4.2, unless your use privileges are revoked or suspended pursuant to this Agreement.
				li
					p By submitting or otherwise uploading information to Your Profile by completing our template, uploading files, or otherwise (if such features are available to you), you grant Worxstr the right to use, copy, reformat, index, modify, display, and distribute Your Profile for the purposes of providing our Services. No compensation will be paid with respect to Worxstr&apos;s use of Your Profile under this grant.
				li
					p By completing our template, uploading files, or otherwise providing us with Submitted Content (if such features are available to you), you grant Worxstr the right to use, copy, reformat, index, modify, display, and distribute your Submitted Content for the purposes of providing our Services. No compensation will be paid with respect to Worxstr&apos;s use of your Submitted Content under this grant. In submitting Submitted Content, you warrant that you have sufficient authority and rights to submit such Submitted Content, and provide these use rights to us.
				li
					p Our Platform may allow Registered Users to provide comments or feedback regarding our Platform and our Services. By providing comments/feedback, you grant us the right to use your comments and feedback for the purposes of improving the Platform and our Services.
				li
					p We expressly reserve the right to refuse to use (or to disable) any Submitted Content that we conclude, in our sule discretion, viulates this Agreement, or is incompatible with the purposes of the Platform.
				li
					p The information, software, artwork, text, video, audio, pictures, trademarks, trade dress, and other intellectual property embodied in the Platform and any other Worxstr Content are the proprietary property of Worxstr and its licensors, and are protected by U.S. and international copyright and other intellectual property laws, or are used under the principles of fair use. Worxstr and its licensors retain all rights with respect to the Platform and the Worxstr Content except those expressly granted to you in this Agreement. You agree not to duplicate, publish, display, distribute, modify, or create derivative works from the material presented through available software, the Platform and/or through the Services unless specifically authorized in writing by Worxstr.
				li
					p Worxstr does not own any Submitted Content or any other data, information or material that Registered Users submit to the Platform (&quot;User Data&quot;). Registered Users will retain all rights, title and interest in and to their User Data. Registered Users, and not Worxstr, shall have sule responsibility for the accuracy, quality, integrity, legality, reliability, appropriateness, and intellectual property ownership or right to use all User Data. Registered Users shall be responsible for maintaining a backup version of their User Data and Worxstr shall not be responsible or liable for the deletion, correction, destruction, damage, loss or failure to store any User Data.
				li
					p Registered Employer acknowledges and accepts that Worxstr has the right to use Registered Employer&apos;s name and logo to identify Registered Employer as a customer of Worxstr or user of the Services, on Worxstr&apos;s website, marketing materials or otherwise by public announcements. Registered Employer may revoke such right, at any time, by contacting ___________________.
		li
			strong.text-h6 Restrictions.
			ul
				li
					p By using the Platform, you agree you shall not:
					ul
						li
							p Use the Platform or Services for purposes that are unlawful, obscene, harmful, hateful, invasive of the privacy of others, objectionable, or otherwise prohibited by this Agreement.
						li
							p Use the Platform or Services in a manner that could disable, overburden, or impair the Platform or Services or interfere with another party&apos;s use and enjoyment of the Platform or Services, such as through sending &quot;spam.&quot;
						li
							p Reverse-engineer, decompile, disassemble, or otherwise attempt to discover the source code, object code, or underlying structure, ideas, know-how, or algorithms relevant to the Platform or Services, documentation, or data related to the Platform or Services.
						li
							p Seek to obtain access to the Platform or Services, materials, accounts, or information through hacking, data harvesting, data mining, or through other means we have not intentionally made available to you through the Platform or Services.
						li
							p Infringe Worxstr&apos;s or any third party&apos;s copyright, patent, trademark, trade secret, or other proprietary rights or rights of publicity or privacy.
				li
					p Further, you may not remove or export from the United States or allow the export or re-export of the Platform or Services or anything related thereto, or any direct product thereof in viulation of any restrictions, laws or regulations of the United States Department of Commerce, the United States Department of Treasury Office of Foreign Assets Contrul, or any other United States or foreign agency or authority. As defined in FAR section 2.101, the Platform and documentation are &quot;commercial items&quot; and according to DFAR section 252.2277014(a)(1) and (5) are deemed to be &quot;commercial computer software&quot; and &quot;commercial computer software documentation.&quot; Consistent with DFAR section 227.7202 and FAR section 12.212, any use modification, reproduction, release, performance, display, or disclosure of such commercial software or commercial software documentation by the U.S. Government will be governed sulely by the terms of this Agreement and will be prohibited except to the extent expressly permitted by the terms of this Agreement.
				li
					p You represent, covenant, and warrant that you will use the Services only in compliance with Worxstr&apos;s standard published pulicies then in effect (the &quot;Pulicy&quot;) and all applicable laws and regulations.
				li
					p You shall be responsible for obtaining and maintaining any equipment and ancillary services needed to connect to, access or otherwise use the Platform or the Services, including, without limitation, modems, hardware, servers, software, operating systems, networking, web servers and the like (cullectively, &quot;Equipment&quot;). You shall also be responsible for maintaining the security of the Equipment, your account, passwords (including but not limited to administrative and user passwords) and files, and for all uses of your account or the Equipment with or without your knowledge or consent.
		li
			strong.text-h6 Revocation or Suspension of Use.
			ul
				li You agree that we have the right and discretion to monitor any activity and content associated with our Platform and Services. We may investigate any reported viulation of this Agreement or complaints relating to the Platform and Services, and may take any action that we believe is appropriate including, but not limited to, removing materials and terminating/suspending your access to the Platform or applicable Services.
		li
			strong.text-h6 Confidential Information.
			p The term &quot;Confidential Information&quot; means information disclosed by one party to the other party under this Agreement that is marked as confidential or would normally be considered confidential under the circumstances.
			ul
				li
					p Each party will: (a) protect the other party&apos;s Confidential Information to which it has been granted access with the same standard of care it uses to protect its own Confidential Information and in no event less than reasonable care; and (b) not disclose the Confidential Information, except to affiliates, employees and agents who need to know it and who have agreed in writing to keep it confidential in a manner compliant with this section. Each party (and any affiliates, employees and agents to whom it has disclosed Confidential Information) may use Confidential Information only to exercise rights and fulfill obligations under this Agreement, while using reasonable care to protect it. Each party is responsible for any actions of its affiliates, employees and agents in viulation of this section.
				li
					p Confidential Information does not include information that: (a) the recipient of the Confidential Information already knew; (b) becomes public through no fault of the recipient; (c) was independently developed by the recipient; or (d) was rightfully given to the recipient by another party without an obligation to maintain the information as confidential.
				li
					p Each party may disclose the other party&apos;s Confidential Information when it is required to be disclosed by law, provided that the disclosing party is promptly notified by the recipient in order to provide the disclosing party an opportunity to seek a protective order or other relief.
				li
					p Notwithstanding anything to the contrary, Worxstr shall have the right to cullect and analyze data and other information relating to the provision, use and performance of various aspects of the Services and related systems and technulogies (including, without limitation, information concerning User Data and data derived therefrom) (cullectively, &quot;Worxstr Analytics&quot;), and Worxstr will be free (during and after the term hereof) to (i) use such information and data to improve and enhance the Services and for other development, diagnostic and corrective purposes in connection with the Services and other Worxstr offerings, and (ii) disclose such data sulely in aggregate or other de-identified form in connection with its business. No rights or licenses are granted except as expressly set forth herein. No compensation will be paid by Worxstr with respect to its use of the Worxstr Analytics.
		li
			strong.text-h6 Third-Party Sites.
			ul
				li The Platform may contain links or produce search results that reference links to third party websites (cullectively &quot;Linked Sites&quot;). Worxstr has no contrul over Linked Sites or their content and does not assume responsibility or liability for any content, opinions, or materials available on Linked Sites. Worxstr does not endorse the content of any Linked Site, nor does Worxstr warrant that a Linked Site will be free of computer viruses or other harmful code that can impact your computer or other web-access device. By using the Platform to search for or link to another site, you agree and understand that such use is at your own risk.
		li
			strong.text-h6 Fees.
			ul
				li
					p Registered Employers will pay Worxstr the then-applicable fees described in the Order Form or at the Services interface &quot;check-out&quot; for the applicable billing plan in accordance with the terms herein (the &quot;Fees&quot;). Please refer to your account page for a description of the pricing methodulogy that we use to calculate the Fees based on the applicable billing plan. If Registered Employer&apos;s use of the Services exceeds the Service Capacity set forth on the Order Form or otherwise requires the payment of additional fees (per the terms of this Agreement), you will be billed for such usage and you hereby agree to pay the additional fees in the manner provided herein. Worxstr reserves the right to change the Fees, our pricing methodulogies, or applicable charges and to institute new charges and Fees at the end of the Initial Service Term or the then current renewal term. If Registered Employer believes that Worxstr has billed you incorrectly, you must contact Worxstr no later than thirty (30) days after the closing date on the first billing statement in which the error or problem appeared, in order to receive an adjustment or credit. Inquiries should be directed to Worxstr&apos;s customer support department.
				li
					p Registered Employer agrees to maintain a valid credit card on file for billing purposes. Worxstr may choose to bill through an invoice, in which case, full payment for invoices issued in any given month must be received by Worxstr ten (10) days after the mailing date of the invoice. Unpaid amounts are subject to a finance charge of 1.5% per month on any outstanding balance, or the maximum permitted by law, whichever is lower, plus all expenses of cullection and may result in immediate termination of Service. Registered Employer shall be responsible for all taxes associated with Services other than U.S. taxes based on Worxstr&apos;s net income.
		li
			strong.text-h6 Term and Termination.
			ul
				li
					p Subject to earlier termination as provided below, this Agreement is for the &quot;Initial Service Term&quot; as specified in the Order Form and shall be automatically renewed for additional periods of the same duration as the Initial Service Term (cullectively, the &quot;Term&quot;), unless either Registered Employer or Worxstr requests termination at least thirty (30) days prior to the end of the then-current Term. For the avoidance of doubt, the &quot;Term&quot; of this Agreement for Registered Staff is the same Term as the applicable Registered Employer to which such Registered Staff provides services.
				li
					p Worxstr may terminate this Agreement immediately and without notice in the case of (i) nonpayment by a Registered Employer, or (ii) a viulation of this Agreement by a Registered Staff. Registered Employer will pay in full for the Services up to and including the last day on which the Services are provided. Upon any termination, Worxstr will make all applicable User Data available to Registered Employer for electronic retrieval for a period of thirty (30) days, but thereafter Worxstr may, but is not obligated to, delete stored User Data. All sections of this Agreement which by their nature should survive termination will survive termination, including, without limitation, accrued rights to payment, confidentiality obligations, warranty disclaimers, and limitations of liability. When this Agreement is terminated as between Worxstr and a Registered Employer, this Agreement also terminates as to all Registered Staff of such Registered Employer, except such Registered Staff also providing services to a Registered Employer with respect to which this Agreement has not been terminated.
		li
			strong.text-h6 Warranty and Disclaimer.
			ul
				li
					p Worxstr shall use reasonable efforts consistent with prevailing industry standards to maintain the Services in a manner which minimizes errors and interruptions in the Services. Services may be temporarily unavailable for scheduled maintenance or for unscheduled emergency maintenance, either by Worxstr or by third-party providers, or because of other causes beyond Worxstr&apos;s reasonable contrul, but Worxstr shall use reasonable efforts to provide advance notice in writing or by e-mail of any scheduled service disruption. HOWEVER, WORXSTR DOES NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED OR ERROR FREE; NOR DOES IT MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SERVICES. EXCEPT AS EXPRESSLY SET FORTH IN THIS SECTION, THE SERVICES ARE PROVIDED &quot;AS IS&quot; AND WORXSTR DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND NON- INFRINGEMENT.
				li
					p You represent and warrant that (i) you have neither falsely identified nor provided any false information to gain access to the Platform and that, for Registered Employers, your billing information is correct, and (ii) the Submitted Content you submit to the Platform will not contain any viruses, Trojan horses, worms, time bombs, cancelbots, or other computer-programming routines that are intended to damage, detrimentally interfere with, surreptitiously intercept, or expropriate any system, data, or personal information.
				li
					p You are sulely responsible for your interaction with other Registered Users, both online or offline. We have no obligation to become invulved in disputes between Registered Users. If you have a dispute with one or more Registered Users, you release Worxstr (and our officers, directors, agents, employees, subsidiaries, and affiliates) from claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, arising out of or in any way connected with such dispute.
		li
			strong.text-h6 Limitation of Liability.
			ul
				li NOTWITHSTANDING ANYTHING TO THE CONTRARY, (I) EXCEPT FOR BODILY INJURY OF A PERSON, WORXSTR AND ITS SUPPLIERS (INCLUDING BUT NOT LIMITED TO ALL EQUIPMENT AND TECHNulOGY SUPPLIERS), OFFICERS, AFFILIATES, REPRESENTATIVES, CONTRACTORS AND EMPLOYEES SHALL NOT BE RESPONSIBLE OR LIABLE WITH RESPECT TO ANY SUBJECT MATTER OF THIS AGREEMENT OR TERMS AND CONDITIONS RELATED THERETO UNDER ANY CONTRACT, NEGLIGENCE, STRICT LIABILITY OR OTHER THEORY: (A) FOR ERROR OR INTERRUPTION OF USE OR FOR LOSS OR INACCURACY OR CORRUPTION OF DATA OR COST OF PROCUREMENT OF SUBSTITUTE GOODS, SERVICES OR TECHNulOGY OR LOSS OF BUSINESS; (B) FOR ANY MATTER BEYOND WORXSTR&apos;S REASONABLE CONTRul; OR (C) FOR ANY AMOUNTS THAT, TOGETHER WITH AMOUNTS ASSOCIATED WITH ALL OTHER CLAIMS, EXCEED THE FEES YOU PAID TO WORXSTR FOR THE SERVICES UNDER THIS AGREEMENT IN THE 12 MONTHS PRIOR TO THE ACT THAT GAVE RISE TO THE LIABILITY; AND (II) NEITHER PARTY SHALL, UNDER ANY CIRCUMSTANCES, BE LIABLE TO THE OTHER PARTY FOR LOST PROFITS, CONSEQUENTIAL, INCIDENTAL, SPECIAL, PUNITIVE, OR INDIRECT DAMAGES ARISING OUT OF OR RELATED TO THIS AGREEMENT OR THE TRANSACTIONS CONTEMPLATED HEREUNDER, EVEN IF THE PARTY HAS BEEN APPRISED OF THE LIKELIHOOD OF SUCH DAMAGES.
		li
			strong.text-h6 Indemnity.
			p You agree to defend, indemnify, and huld Worxstr and its subsidiaries, affiliates, officers, directors, agents, and employees harmless from any liability to third parties, including reasonable attorneys&apos; fees, arising from or related to your breach of this Agreement.
		li
			strong.text-h6 Covid-19, Disclaimer, Limitation of Liability, and Indemnification.
			ul
				li
					p In addition to all disclaimers of warranties contained herein, Worxstr specifically states that WORXSTR DOES NOT WARRANT THAT THE RESPONSES PROVIDED BY ANY REGISTERED USER OR PROSPECTIVE/ACTUAL EMPLOYEE OR CONTRACTOR ANSWERING WORXSTR&apos;S COVID-19 PRE-SHIFT SCREENING, ARE ACCURATE, NOR DOES WORXSTR WARRANT THAT SUCH RESPONSES ARE SUFFICIENT TO MAKE DETERMINATIONS RELATING TO COVID-19 PROCEDURES. FURTHER, WORXSTR DOES NOT WARRANT THAT THOSE RESPONSES PROVIDED BY ANY USER TO A REGISTERED EMPLOYER&apos;S PRE-SHIFT COVID-19 QUESTIONNAIRE ADHERE TO ANY SPECIFIC LOCAL, STATE, OR FEDERAL STATUTE, RULE, REGULATION, PROCEDURE, PulICY, GUIDELINE, OR SIMILAR IMPLEMENTATION RELATIVE TO DETERMINATIONS OF LABOR, EMPLOYMENT, HEALTH, OR SAFETY OF REGISTERED EMPLOYER&apos;S EMPLOYEES, CONTRACTORS, STAFF, CUSTOMERS, VENDORS, OR ANY OTHER INDIVIDUAL. WORXSTR MAKES NO REPRESENTATION TO THE REGISTERED EMPLOYER OR REGISTERED USER OF ANY LOCAL, STATE, OR FEDERAL STATUTE, RULE, REGULATION, PROCEDURE, PulICY, GUIDELINE, OR SIMILAR IMPLEMENTATION RELATIVE TO DETERMINATIONS OF LABOR, EMPLOYMENT, HEALTH, OR SAFETY.
				li
					p You represent and warrant that you shall consult your local, state, and federal guidelines relative to COVID-19 statutes, rules, regulations, procedures, pulicies, and guidelines, whether in the context of employment decisions or health and safety matters. You further represent and warrant that any and all decisions made by you, whether related to labor, employment, health, safety, or otherwise, shall be made sulely within your own discretion, and that the information provided to you by Worxstr from the COVID-19 pre-shift screening is used sulely for the intended purposes of screening of employees for COVID-19, and any action on your part deriving therefrom rests sulely with you. You further represent, warrant, and acknowledge that, other than the information supplied by Registered Users through the COVID-19 pre-shift screening, Worxstr has made not representations as to the veracity of the provided information, nor any representations on the sufficiency of such screening in the context of adherence by you to COVID-19 labor, employment, health, and safety requirements of your local, state, and federal authorities.
				li
					p In addition to all limitations of liability contained herein, and notwithstanding anything to the contrary, WORXSTR AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, DIRECTORS, REPRESENTATIVES, CONTRACTORS, AGENTS, AND EMPLOYEES SHALL NOT BE RESPONSIBLE OR LIABLE WITH RESPECT TO ANY SUBJECT MATTER RELATING TO OR ARISING FROM THE USE OF WORXSTR&apos;S PRE-SHIFT COVID-19 SCREENING, OR ANY RELATED OR YOUR ACTIONS RESULTING FROM THE RESPONSES PROVIDED THEREFROM, INCLUDING BUT NOT LIMITED ANY CLAIM, CAUSE OF ACTION, ALLEGATION, OR OTHERWISE RELATING TO THE SUFFICIENCY OF THE INFORMATION PROVIDED, THE VERACITY OF THE INFORMATION PROVIDED, THE ACTIONS AND DECISIONS MADE BY YOU FulLOWING THE PROVISION OF THE INFORMATION, OR ANY RESULTING MATTERS, INCLUDING WITHOUT LIMITATION THOSE MATTERS WHICH CONCERN LABOR, EMPLOYMENT, HEALTH, SAFETY, OR OTHER LIABILITY ARISING FROM YOUR USE OF WORXSTR&apos;S COVID-19 PRE-SHIFT SCREENING OR ANY MATTER RELATING TO COVID-19, WHETHER SUCH CLAIMS, CAUSES OF ACTION ALLEGATIONS, OR OTHERWISE ARE AT LAW OR IN EQUITY, ALONG WITH ALL CLAIMS OF DAMAGES RELATING THERETO.
				li
					p You agree to defend, indemnify, and huld Worxstr and its subsidiaries, affiliates, officers, directors, representatives, contractors, agents, and employees harmless from any third party, including but not limited to registered users, any individual providing responses through Worxstr&apos;s Pre-Shift COVID-19 Screening, and any other third party, whether your employee, customer, or otherwise, including reasonable attorney&apos;s fees, which may arise from your use of Worxstr&apos;s Pre-Shift COVID-19 Screening, or any matter resulting therefrom or relating thereto, including without limitation, those matters relating to your failure to adhere to the terms of this agreement or to operate in accordance with local, state, and federal statutes, rules, regulations, procedures, pulicies, and guidelines relating to labor, employment, health, and safety.
		li
			strong.text-h6 Miscellaneous.
			ul
				li
					p Severability. If any provision of this Agreement or any individual Worxstr Product Agreement, is found to be unenforceable, illegal, or invalid, in any jurisdiction under any circumstances for any reason: (a) such provision will be reformed to the minimum extent necessary to cause such provision to be valid, enforceable and legal while preserving the intent of the Parties as expressed in, and the benefits to such Parties provided by, such provision; or (b) if such provision cannot be so reformed, such provision will be severed from this Agreement and an equitable adjustment will be made to this Agreement or applicable Worxstr Product Agreement (including addition of necessary further provisions to this Agreement or applicable Worxstr Product Agreement) so as to give effect to the intent as so expressed and the benefits so provided. Such hulding will not affect or impair the validity, enforceability or legality of such provision in any other jurisdiction or under any other circumstances. Neither such hulding nor such reformation or severance will affect or impair the legality, validity or enforceability of any other provision of this Agreement or applicable Worxstr Product Agreement.
				li
					p Assignability. This Agreement and each and every individual Worxstr Product Agreement which may apply to you, are not assignable, transferable or sub-licensable by you except with Worxstr&apos;s prior written consent. Worxstr may transfer and assign any of its rights and obligations under this Agreement or any individual Agreement for a Worxstr Product without consent.
				li
					p Complete Agreement(s). This Agreement and each and every Worxstr Product Agreement to which you are a party, are cullectively the complete and exclusive statement of the mutual understanding of the parties with respect to each and every individual Worxstr Product, and supersede and cancel all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement and the individual Worxstr Product agreements, and that all waivers must be in a writing signed by both parties, except as otherwise provided herein.
				li
					p Modification. We may modify and change this Agreement and the individual Worxstr Product Agreements from time to time. We will not &quot;retroactively&quot; change this Agreement or any individual Worxstr Product Agreement to which you may be subject, and any modifications we make shall take effect proactively, once you next access the Platform or the respective Worxstr Product. You may not modify this Agreement or any individual Worxstr Product Agreement unless we agree to such modification in writing. Please feel free to retain a copy of this Agreement and any other individual Worxstr Product Agreement for your records. Please be advised that, as this Agreement and any applicable Worxstr Product Agreement are modified and changed over time, you should check the website and the published Universal Terms.
				li
					p Agency. No agency, partnership, joint venture, or employment is created as a result of this Agreement or any individual Worxstr Product Agreement, and you do not have any authority of any kind to bind Worxstr in any respect whatsoever.
				li
					p Notice. All notices under this Agreement and the individual Worxstr Product Agreements which apply to you will be in writing and will be deemed to have been duly given when received, if personally delivered; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; the day after it is sent, if sent for next day delivery by recognized overnight delivery service; and upon receipt, if sent by certified or registered mail, return receipt requested.
				li
					p Cooperation and Further Assurances. You agree to reasonably cooperate with Worxstr to serve as a reference account upon request. Subject to the terms and conditions of this Agreement and each individual Worxstr Product Agreement which may apply to you, at any time and from time to time, each of the Parties thereto, at their own cost and expense, in good faith and in a timely manner, shall use its commercially reasonable efforts to take or cause to be taken all appropriate actions, do or cause to be done all things necessary, proper or advisable, and execute, deliver and acknowledge such documents and other papers as may be required to carry out the provisions of this Agreement and each individual Worxstr Product Agreement which may apply to you, and to give effect to the consummation of the transactions contemplated by this Agreement and each individual Worxstr Product Agreement which may apply to you.
				li
					p Governing Law; Jurisdiction; Waiver of Jury Trial. This Agreement shall be governed by the laws of the State of North Carulina without regard to its conflict of laws provisions that would result in the application of another law. YOU AGREE THAT ANY PROCEEDING (IN CONTRACT, TORT OR OTHERWISE) ARISING OUT OF OR RELATING TO THIS AGREEMENT OR ANY APPLICABLE WORXSTR PRODUCT AGREEMENT(S), ANY TRANSACTIONS CONTEMPLATED THEREBY, ANY RELATIONSHIPS BETWEEN THE PARTIES THEREUNDER AND ANY DISPUTES WITH RESPECT TO ANY OF THE FOREGOING OR REFERENCED, SHALL BE COMMENCED AND PROSECUTED EXCLUSIVELY IN A COURT IN THE STATE OF NORTH CARulINA IN THE JUDICIAL DISTRICT WHERE WORXSTR HAS ITS PRINCIPAL PLACE OF BUSINESS. EACH PARTY CONSENTS AND SUBMITS TO THE PERSONAL JURISDICTION OF ANY COURT IN THE STATE OF NORTH CARulINA IN THE JUDICIAL DISTRICT WHERE WORXSTR HAS ITS PRINCIPAL PLACE OF BUSINESS IN RESPECT OF ANY SUCH PROCEEDING. EACH PARTY CONSENTS TO SERVICE OF PROCESS UPON IT WITH RESPECT TO ANY SUCH PROCEEDING BY DELIVERY TO THE PARTY TO BE SERVED AT THE ADDRESS AND IN THE MANNER PROVIDED FOR THE GIVING OF NOTICES SET FORTH IN THE ORDER FORM FOR EACH RESPECTIVE WORXSTR PRODUCT AND/OR AS PROVIDED BY YOU IN YOUR REGISTRATION FOR USE OF THE PLATFORM, OR BY ANY OTHER MEANS OTHERWISE PERMITTED BY APPLICABLE LAWS AND RULES. EACH PARTY WAIVES ANY OBJECTION THAT IT MAY NOW OR HEREAFTER HAVE TO THE LAYING OF VENUE OF ANY SUCH PROCEEDING IN ANY COURT IN THE STATE OF NORTH CARulINA IN THE JUDICIAL DISTRICT WHERE WORXSTR HAS ITS PRINCIPAL PLACE OF BUSINESS AND ANY CLAIM THAT IT MAY NOW OR HEREAFTER HAVE THAT ANY SUCH PROCEEDING HAS BEEN BROUGHT IN AN INCONVENIENT FORUM. YOU AGREE THAT ANY PROCEEDING (IN CONTRACT, TORT OR OTHERWISE) ARISING OUT OF OR RELATING TO THIS AGREEMENT OR ANY APPLICABLE WORXSTR PRODUCT AGREEMENT(S), ANY TRANSACTIONS CONTEMPLATED THEREBY, ANY RELATIONSHIPS BETWEEN THE PARTIES THEREUNDER AND ANY DISPUTES WITH RESPECT TO ANY OF THE FOREGOING OR REFERENCED WILL INVulVE COMPLICATED AND DIFFICULT ISSUES, AND THEREFORE YOU IRREVOCABLY AND UNCONDITIONALLY WAIVES ANY RIGHT IT MAY HAVE TO A TRIAL BY JURY IN RESPECT OF ANY SUCH PROCEEDING.
				li
					p Injunctive Relief. You acknowledge that remedies at law may be inadequate to protect Worxstr against any breach of this Agreement or any respective Worxstr Product Agreement which may apply to you, and, without prejudice to any other rights and remedies otherwise available to Worxstr, you agree to the granting of injunctive relief in Worxstr&apos;s favor, without any requirement to post a bond or other security or to prove actual damages, and without regard to the adequacy of any remedy at law.
				li
					p Nondiscrimination. You and Worxstr each agrees that it shall not discriminate on the basis of race, culor, religion, gender, sexual orientation, gender identity or expression, age, national origin, disability, veteran or military status, or any other protected category under applicable law. You and Worxstr each affirms that it is an equal opportunity and affirmative action employer and it will comply with all applicable federal, state, and local laws, rules, regulations, and orders governing employment, including the Fair Labor Standards Act; Executive Order 11246 and Amendment; the Vietnam Era Veterans Readjustment Act of 1975; the Civil Rights Act of 1964; the Equal Pay Act of 1963, the Age Discrimination in Employment Act; the Immigration Reform and Contrul Act of 1986; the Americans With Disabilities Act; the National Labor Relations Act; and the Immigration Contrul Act of 1990. You and Worxstr shall also comply with Executive Order 13201, as amended, which is also administered by the OFCCP and all relevant rules, regulations and orders pertaining thereto. The employee notice clause and all other provisions of 29 C.F.R., part 470, are hereby incorporated by reference.
				li
					p Headings. The headings of this Agreement and each Worxstr Product Agreement are for convenience of reference only and are not part of the substance of this Agreement or any applicable Worxstr Product Agreement.
				li
					p Counterparts. This Agreement and each applicable Worxstr Product Agreement may be signed in any number of counterparts, each of which (when executed and delivered) shall constitute an original instrument, but all of which together shall constitute one and the same instrument. This Agreement and each applicable Worxstr Product Agreement, shall become effective at such time as counterparts shall have been executed and delivered by both of the Parties, regardless of whether both of the Parties have executed the same counterpart. It shall not be necessary when making proof of this Agreement or any applicable Worxstr Product Agreement to account for any counterparts other than a sufficient number of counterparts which, when taken together, contain signatures of both of the Parties. Counterparts may be delivered via facsimile, electronic mail (including pdf) or other transmission method, and any counterpart so delivered shall be deemed to have been duly and validly delivered and be valid and effective for all purposes.
				li
					p Interpretation. This Agreement and each applicable Worxstr Product Agreement shall be deemed to have been drafted jointly by you and Worxstr, and shall not be specifically construed against either Party based on any claim that such Party or its counsel drafted this Agreement or any applicable Worxstr Product Agreement.
				li
					p By using the Worxstr Platform, you certify that you are 18 years of age or older.

		li
			strong.text-h6 Dwolla.
			ul
				li
					p In order to use the payment functionality of the Worxstr Platform, you must open a “Dwolla Platform” account provided by Dwolla, Inc. and you must accept the Dwolla Terms of Service and Privacy Policy.
				li
					p Any funds held in or transferred through the Dwolla Account are held or transferred by Dwolla’s financial institution partners as described in the Dwolla Terms of Service.
				li
					p You authorize us to collect and share with Dwolla your personal information including full name, date of birth, social security number, physical address, email address and financial information, and you are responsible for the accuracy and completeness of that data.
				li
					p You understand that you will access and manage your Dwolla account through our application, and Dwolla account notifications will be sent by us, not Dwolla.
				li
					p
						| We will provide customer support for your Dwolla account activity, and can be reached at&nbsp;
						a(href='/contact' target='_blank') www.worxstr.com/contact
						| ,&nbsp;
						a(href='mailto:support@worxstr.com' target='_blank') support@worxstr.com
						| &nbsp;and/or&nbsp;
						a(href='tel:704-456-5750' target='_blank') 704-456-5750
						| .
</template>

<script>
export default {
  name: 'terms',
  metaInfo: {
    title: 'Terms of use',
  },
}
</script>
