name: Cypress Tests with installation job

on:
  push:
    branches:
      - dev
      - main
      - cypress

jobs:
  # install:
  #   runs-on: ubuntu-latest
  #   container: cypress/browsers:node12.18.3-chrome87-ff82
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Cypress install
  #       uses: cypress-io/github-action@v2
  #       with:
  #         # Disable running of tests within install job
  #         runTests: false
  #         build: yarn install

  #     - name: Save dist folder
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: dist
  #         if-no-files-found: error
  #         path: dist
  
  run:
    # needs: install
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     # run copies of the current job in parallel
    #     containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Download the build folders
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: dist
      #     path: dist

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # we have already installed all dependencies above
          # install: false
          install-command: yarn install --silent
          start: yarn serve --silent
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 600
          browser: chrome
          record: true
          # parallel: true
          group: 'UI - Chrome'
          # spec: cypress/tests/ui/*
        env:
          VUE_APP_TEST_MODE: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
            name: cypress-screenshots
            path: |
              cypress/screenshots
              cypress/videos
          
